[package]

name = "scirust"
version = "0.0.2"
authors = ["Shailesh Kumar <shailesh@indigits.com>"]


[dependencies.quickcheck]
git = "https://github.com/BurntSushi/quickcheck"

[dependencies.quickcheck_macros]
git = "https://github.com/BurntSushi/quickcheck"




[[bin]]

name = "scirust_main"
doc = false
