[package]
name = "sropt"
version = "0.1.0"
authors = ["Shailesh Kumar <shailesh@indigits.com>"]

[dependencies]
log = "0.3.1"
rand = "0.3.7"
num = "0.1.36"
bencher = "*"


[lib]
bench = false

[[bench]]
name = "example"
harness = false
